apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secretpod
  name: secretpod
spec:
  containers:
  - image: nginx
    name: secretpod
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-password-secret
            key: dbpassword
    volumeMounts:
    - name: dbsecret
      mountPath: "/etc/k8s-secrets"
      readOnly: true
    resources: {}
  volumes:
  - name: dbsecret
    secret:
      secretName: db-password-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
