apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: sidecar-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    run: sidecar-demo
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar-demo
  name: sidecar-demo
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /var/log/nginx/
      name: log-volume
    resources: {}
  - image: busybox
    name: logaggregator
    args: [/bin/sh, -c, 'tail -f /var/log/nginx/error.log>/var/log/nginx/nginx.errors']
    volumeMounts:
    - mountPath: /var/log/nginx/
      name: log-volume
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: log-volume
    emptyDir: {}
status: {}
